from __future__ import annotations

import argparse
import json
from dataclasses import asdict
import os
import re
import sys
import termios
import tty
from typing import Any

from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table

from . import __version__
from .astmap import analyze_files
from .explainer import ExplanationResult, generate_explanation
from .diffparse import files_from_unified_diff
from .github import GitHubClient, GitHubError
from .models import ChangedFile, PRMetadata, TriageResult
from .triage import compute_flags, verdict_for

console = Console()
VERDICT_STYLES = {"SHIP": "bold green", "QUARANTINE": "bold yellow", "BLOCK": "bold red"}


def positive_pr_number(value: str) -> int:
    """Parse a GitHub pull-request number, rejecting impossible values early."""
    try:
        number = int(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("PR number must be an integer") from exc
    if number < 1:
        raise argparse.ArgumentTypeError("PR number must be greater than zero")
    return number


def parse_repo(value: str) -> tuple[str, str]:
    value = value.rstrip("/")
    if value.startswith("https://github.com/"):
        value = value.split("https://github.com/", 1)[1]
    if value.startswith("github.com/"):
        value = value.split("github.com/", 1)[1]
    parts = value.split("/")
    if len(parts) != 2 or not all(parts) or any(not re.fullmatch(r"[A-Za-z0-9_.-]+", part) for part in parts):
        raise argparse.ArgumentTypeError("repository must look like owner/repo")
    return parts[0], parts[1]


def summarize_checks(check_runs: dict[str, Any], status: dict[str, Any]) -> dict[str, Any]:
    runs = check_runs.get("check_runs", [])
    failed = []
    pending = []
    for run in runs:
        conclusion = run.get("conclusion")
        name = run.get("name", "unnamed check")
        if conclusion in {"failure", "cancelled", "timed_out", "action_required", "startup_failure"}:
            failed.append(name)
        elif conclusion not in {"success", "skipped", "neutral"}:
            pending.append(name)
    combined_state = status.get("state")
    if combined_state in {"failure", "error"}:
        failed.append("combined commit status")
    elif combined_state == "pending":
        pending.append("combined commit status")
    statuses = status.get("statuses", [])
    for item in statuses:
        state = item.get("state")
        context = item.get("context", "unnamed status")
        if state in {"failure", "error"}:
            failed.append(context)
        elif state == "pending":
            pending.append(context)
    if failed:
        state = "failure"
    elif pending:
        state = "pending"
    elif runs or statuses:
        state = "success"
    else:
        state = "unknown"
    return {"state": state, "failed": sorted(dict.fromkeys(failed)), "pending": sorted(dict.fromkeys(pending)), "count": len(runs) + len(statuses)}


def _risk_badge(severity: str) -> str:
    return {"critical": "CRITICAL", "high": "HIGH", "medium": "MEDIUM", "low": "LOW"}.get(severity, severity.upper())


def render_explanation(explanation: ExplanationResult) -> list[str]:
    lines = ["## Literate diff — generated explanation", ""]
    if explanation.error:
        lines.extend([
            f"> Generated explanation unavailable: {explanation.error}",
            f"> Redactions applied before any model call: {explanation.redactions}",
            "",
        ])
        return lines
    lines.extend([
        f"> Generated by `{explanation.model}` from bounded, redacted context. This prose cannot change the deterministic verdict.",
        f"> Redactions applied before the model call: {explanation.redactions}",
        "",
        "### Background",
        "",
        explanation.explanation["background"],
        "",
        "### Intent in plain language",
        "",
        explanation.explanation["intent"],
        "",
        "### Narrative",
        "",
    ])
    for index, step in enumerate(explanation.explanation["narrative"], start=1):
        lines.append(f"#### {index}. {step['title']}")
        lines.append("")
        lines.append(step["explanation"])
        if step["files"]:
            lines.append(f"- Files: {', '.join(f'`{path}`' for path in step['files'])}")
        if step["evidence"]:
            lines.append(f"- Evidence: {'; '.join(step['evidence'])}")
        if step["snippet"]:
            lines.extend(["", "```text", step["snippet"], "```"])
        lines.append("")
    if explanation.explanation["review_questions"]:
        lines.extend(["### Review questions", ""])
        lines.extend(f"- {question}" for question in explanation.explanation["review_questions"])
        lines.append("")
    if explanation.explanation["uncertainties"]:
        lines.extend(["### Uncertainties", ""])
        lines.extend(f"- {item}" for item in explanation.explanation["uncertainties"])
        lines.append("")
    return lines


def render_markdown(result: TriageResult, explanation: ExplanationResult | None = None) -> str:
    m = result.metadata
    lines = [
        f"# PR triage: [{m.owner}/{m.repo}#{m.number}]({m.html_url})",
        "",
        f"**Title:** {m.title}",
        f"**Author:** @{m.author}  ",
        f"**Refs:** `{m.base_ref}` ← `{m.head_ref}`  ",
        f"**Commits:** {m.commits} · **Files:** {m.changed_files} · **Lines:** +{m.additions} / -{m.deletions}",
        "",
        "## Verdict",
        "",
        f"# **{result.verdict}**",
        "",
        *[f"- {reason}" for reason in result.reasoning],
        "",
        "## Checks",
        "",
        f"- State: **{result.checks.get('state', 'unknown').upper()}**",
        f"- Observed checks: {result.checks.get('count', 0)}",
    ]
    if result.checks.get("failed"):
        lines.append(f"- Failed: {', '.join(f'`{x}`' for x in result.checks['failed'])}")
    if result.checks.get("pending"):
        lines.append(f"- Pending: {', '.join(f'`{x}`' for x in result.checks['pending'])}")

    lines += ["", "## Risk flags", ""]
    if result.flags:
        for flag in result.flags:
            lines.append(f"### `{flag.code}` — {_risk_badge(flag.severity)}")
            lines.append(flag.message)
            for evidence in flag.evidence[:20]:
                lines.append(f"- `{evidence}`")
            lines.append("")
    else:
        lines.append("No deterministic risk flags fired.")

    lines += ["", "## Blast-radius map", "", "The Phase 1 map is conservative: it identifies changed files, changed symbols, and direct call sites visible in changed hunks. A full repository-wide call graph is a Phase 2 enhancement.", ""]
    for file in result.files:
        lines.append(f"### `{file.path}` ({file.status}, +{file.additions}/-{file.deletions})")
        symbols = ", ".join(f"`{x}`" for x in file.touched_symbols) if file.touched_symbols else "none detected"
        callers = ", ".join(f"`{x}`" for x in file.callers) if file.callers else "none detected in changed hunks"
        tests = ", ".join(f"`{x}`" for x in file.tests_found) if file.tests_found else "none detected"
        lines.append(f"- Touched symbols: {symbols}")
        lines.append(f"- Direct callers: {callers}")
        lines.append(f"- Related tests: {tests}")
        lines.append("")

    if explanation is not None:
        lines += [""] + render_explanation(explanation)

    lines += ["## Changed-file inventory", "", "| File | Status | Additions | Deletions | Symbols |", "| --- | --- | ---: | ---: | --- |"]
    for file in result.files:
        symbols = ", ".join(file.touched_symbols) if file.touched_symbols else "—"
        lines.append(f"| `{file.path}` | {file.status} | {file.additions} | {file.deletions} | {symbols} |")
    lines += ["", "## Deterministic policy", "", "- `BLOCK`: failed checks or authentication/secrets/security-sensitive changes.", "- `QUARANTINE`: database changes, dependency changes, missing obvious test coverage, or unavailable/pending checks.", "- `SHIP`: no rules fired and observed checks passed.", "", "_Generated by diffly-cli. Deterministic triage is authoritative; any literate-diff prose is optional generated explanation._"]
    return "\n".join(lines) + "\n"


def _section_lines(result: TriageResult, section: str) -> list[str]:
    """Build a compact Rich-friendly section for the interactive view."""
    if section == "verdict":
        style = VERDICT_STYLES.get(result.verdict, "bold")
        return [f"[{style}]{result.verdict}[/]", *result.reasoning]
    if section == "checks":
        checks = result.checks
        state = checks.get("state", "unknown").upper()
        return [f"State: {state}", f"Observed: {checks.get('count', 0)}", *[f"Failed: {x}" for x in checks.get("failed", [])], *[f"Pending: {x}" for x in checks.get("pending", [])]]
    if section == "risks":
        if not result.flags:
            return ["No deterministic risk flags fired."]
        return [f"{flag.code} ({flag.severity}): {flag.message}" for flag in result.flags]
    return [f"{item.path}  +{item.additions}/-{item.deletions}" for item in result.files[:80]] or ["No changed files returned."]


def interactive_view(result: TriageResult) -> None:
    """Let a reviewer toggle report sections with up/down arrows and space."""
    if not sys.stdin.isatty() or not sys.stdout.isatty():
        console.print("[yellow]Interactive mode needs a terminal; showing the standard report instead.[/]")
        console.print(Markdown(render_markdown(result)))
        return
    labels = [("verdict", "Verdict"), ("checks", "Checks"), ("risks", "Risk flags"), ("files", "Changed files")]
    enabled = {key: True for key, _ in labels}
    cursor = 0
    fd = sys.stdin.fileno()
    old = termios.tcgetattr(fd)
    try:
        tty.setcbreak(fd)
        while True:
            console.clear()
            console.print(Panel.fit("[bold cyan]diffly interactive review[/]  [dim]↑/↓ move · space toggle · enter apply · q quit[/]", border_style="cyan"))
            menu = Table(show_header=False, box=None, padding=(0, 1))
            menu.add_column("", width=3)
            menu.add_column("Section")
            for index, (key, label) in enumerate(labels):
                marker = "[cyan]›[/]" if index == cursor else " "
                state = "[green]on[/]" if enabled[key] else "[dim]off[/]"
                menu.add_row(marker, f"{label:<18} {state}")
            console.print(menu)
            console.print("\n[dim]Toggle sections to keep the review focused.[/]")
            key = sys.stdin.read(1)
            if key in {"q", "Q"}:
                return
            if key in {"\r", "\n"}:
                break
            if key == " ":
                selected = labels[cursor][0]
                enabled[selected] = not enabled[selected]
            elif key == "\x1b":
                sequence = sys.stdin.read(2)
                if sequence == "[A":
                    cursor = (cursor - 1) % len(labels)
                elif sequence == "[B":
                    cursor = (cursor + 1) % len(labels)
        console.clear()
        result_table = Table(title=f"{result.metadata.owner}/{result.metadata.repo}#{result.metadata.number}", box=None)
        result_table.add_column("Section", style="cyan")
        result_table.add_column("Details")
        for key, label in labels:
            if enabled[key]:
                details = "\n".join(_section_lines(result, key))
                result_table.add_row(label, details)
        console.print(result_table)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old)


def build_result(client: GitHubClient, owner: str, repo: str, number: int) -> TriageResult:
    metadata = client.pull_request(owner, repo, number)
    files = client.pull_request_files(owner, repo, number)
    try:
        diff = client.pull_request_diff(owner, repo, number)
    except GitHubError:
        # GitHub refuses raw diffs above its size limit, while the paginated
        # list-files endpoint can still provide useful metadata and patches.
        diff = ""
    if diff and any(not file.patch for file in files):
        fallback_patches = {file.path: file.patch for file in files_from_unified_diff(diff)}
        for file in files:
            if not file.patch and file.path in fallback_patches:
                file.patch = fallback_patches[file.path]
    files = analyze_files(files)
    check_runs = client.check_runs(owner, repo, metadata.head_sha)
    status = client.commit_status(owner, repo, metadata.head_sha)
    checks = summarize_checks(check_runs, status)
    try:
        tree_result = client.repository_tree(owner, repo, metadata.head_sha)
        repo_paths = tree_result.paths
        tree_truncated = tree_result.truncated
    except GitHubError:
        repo_paths = []
        tree_truncated = True
    checks = dict(checks)
    checks["repository_tree_complete"] = not tree_truncated
    if tree_truncated:
        checks["repository_tree_truncated"] = True
    flags = compute_flags(metadata, files, checks, repo_paths)
    verdict, reasoning = verdict_for(flags, checks)
    return TriageResult(metadata, files, flags, verdict, reasoning, checks, "GitHub REST API")


def run_pr(args: argparse.Namespace) -> int:
    owner, repo = args.repository
    client = GitHubClient(token=args.token)
    try:
        result = build_result(client, owner, repo, args.number)
    except GitHubError as exc:
        console.print(Panel.fit(f"[bold red]Unable to inspect pull request[/]\n{exc}\n\n[dim]Check GITHUB_TOKEN, repository access, and network connectivity. Run `diffly doctor` for diagnostics.[/]", border_style="red"))
        return 2
    explanation = generate_explanation(
        result,
        model=args.llm_model,
        base_url=args.llm_base_url,
    ) if args.explain else None
    if args.interactive and not args.json and not args.output:
        interactive_view(result)
        return 0
    output = render_markdown(result, explanation)
    if args.json:
        payload = {
            "metadata": asdict(result.metadata),
            "files": [asdict(file) for file in result.files],
            "flags": [asdict(flag) for flag in result.flags],
            "verdict": result.verdict,
            "reasoning": result.reasoning,
            "checks": result.checks,
            "source": result.source,
            "literate_diff": ({
                "explanation": explanation.explanation,
                "redactions": explanation.redactions,
                "model": explanation.model,
                "error": explanation.error,
            } if explanation is not None else None),
        }
        print(json.dumps(payload, indent=2, sort_keys=True))
    elif args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(output)
        console.print(f"Wrote {args.output}")
    else:
        console.print(Markdown(output))
    return 0


def run_doctor(_: argparse.Namespace) -> int:
    """Print actionable local diagnostics without making a GitHub request."""
    import shutil
    table = Table(title="diffly doctor", box=None)
    table.add_column("Check", style="cyan")
    table.add_column("Status")
    checks = [("Python", f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"), ("GitHub token", "configured" if os.environ.get("GITHUB_TOKEN") else "not set (public API only)"), ("Terminal", "interactive" if sys.stdin.isatty() else "non-interactive"), ("diffly executable", shutil.which("diffly") or "not on PATH")]
    for name, value in checks:
        table.add_row(name, value)
    console.print(table)
    return 0


def run_help(args: argparse.Namespace) -> int:
    args.root_parser.print_help()
    return 0


def run_version(_: argparse.Namespace) -> int:
    console.print(f"[bold cyan]diffly[/] {__version__}")
    return 0


def run_wizard(parser: argparse.ArgumentParser) -> int:
    """Run the zero-argument first-use flow for human reviewers."""
    console.clear()
    console.print(Panel.fit(
        "[bold cyan]diffly[/]  [dim]Pull request intelligence, without the noise[/]\n"
        "[dim]Enter a repository and PR, then use the focused review screen.[/]",
        border_style="cyan",
        padding=(1, 2),
    ))
    console.print("[dim]Tip: scripted usage remains available with `diffly pr OWNER/REPO NUMBER --json`.\n[/]")
    while True:
        raw_repository = Prompt.ask("[cyan]Repository[/]", default=os.environ.get("DIFFLY_REPOSITORY", ""))
        try:
            repository = parse_repo(raw_repository)
            break
        except argparse.ArgumentTypeError as exc:
            console.print(f"[red]Invalid repository:[/] {exc}")
    while True:
        raw_number = Prompt.ask("[cyan]Pull request number[/]")
        try:
            number = positive_pr_number(raw_number)
            break
        except argparse.ArgumentTypeError as exc:
            console.print(f"[red]Invalid PR number:[/] {exc}")
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        console.print("[dim]No GITHUB_TOKEN found. Public repositories still work with lower API limits.[/]")
    explain = Confirm.ask("[cyan]Add an optional generated explanation?[/]", default=False)
    owner, repo = repository
    console.print(Panel.fit(
        f"[bold]Ready[/]  {owner}/{repo}#{number}\n"
        f"[dim]Mode: {'deterministic + explanation' if explain else 'deterministic'} · output: interactive[/]",
        border_style="green",
    ))
    args = argparse.Namespace(
        repository=repository,
        number=number,
        token=token,
        output=None,
        json=False,
        explain=explain,
        llm_model=None,
        llm_base_url=None,
        interactive=True,
    )
    return run_pr(args)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="diffly", description="Deterministic triage for large GitHub pull requests", formatter_class=argparse.RawDescriptionHelpFormatter, epilog="Examples:\n  diffly pr pallets/urllib3 3456\n  diffly pr pallets/urllib3 3456 --interactive\n  diffly doctor")
    subparsers = parser.add_subparsers(dest="command", required=True)
    pr = subparsers.add_parser("pr", help="Analyze one GitHub pull request")
    pr.add_argument("repository", type=parse_repo, metavar="<owner/repo>")
    pr.add_argument("number", type=positive_pr_number, metavar="<pr-number>")
    pr.add_argument("--token", default=None, help="GitHub token; defaults to GITHUB_TOKEN")
    pr.add_argument("--output", help="Write terminal Markdown to a file")
    pr.add_argument("--json", action="store_true", help="Emit structured JSON instead of Markdown")
    pr.add_argument("--explain", action="store_true", help="Add an optional LLM-generated literate-diff explanation")
    pr.add_argument("--llm-model", default=None, help="Override DIFFLY_LLM_MODEL for --explain")
    pr.add_argument("--llm-base-url", default=None, help="Override DIFFLY_LLM_BASE_URL for --explain")
    pr.add_argument("--interactive", action="store_true", help="Open a keyboard-driven report view (arrows, space, enter)")
    pr.set_defaults(func=run_pr)
    doctor = subparsers.add_parser("doctor", help="Diagnose local installation and environment")
    doctor.set_defaults(func=run_doctor)
    version = subparsers.add_parser("version", help="Print the installed diffly version")
    version.set_defaults(func=run_version)
    help_command = subparsers.add_parser("help", help="Show commands, options, and examples")
    help_command.set_defaults(func=run_help, root_parser=parser)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    effective_argv = sys.argv[1:] if argv is None else argv
    if not effective_argv:
        return run_wizard(parser)
    args = parser.parse_args(effective_argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
